// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztvtqxodgffyetxrqatt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0dnRxeG9kZ2ZmeWV0eHJxYXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDI3MzIsImV4cCI6MjA2Nzg3ODczMn0.A4bJ_S05g8ijXtXkOdpDKGjITbuf4BXak8j0zKUVCzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});